### ISSUE TITLE
Exception - Class 'theme_eguru\output\core\context_system' not found

### ISSUE THREAD

**Issue by AdrianoRuseler** [lmsace/eguru#34]
This error occurs in moodle 4.0 when accessing the home page or moodle.site.url/?redirect=0

![image](https://user-images.githubusercontent.com/2466178/168133401-a396e928-5d96-4ce5-8b1c-1c6d2d3ea6c7.png)

**Comment by prasanna-lmsace** [comment]
Hi [AdrianoRuseler](https://github.com/AdrianoRuseler),

Thanks for reporting the issue with us, We have fixed and released the new version in branch v4.0

**Comment by ikexue** [comment]
> Hi [AdrianoRuseler](https://github.com/AdrianoRuseler),
> 
> Thanks for reporting the issue with us, We have fixed and released the new version in branch v4.0

Please help

What can i do to fix it!

I have Moodle [4.0.1 (Build: 20220602)] with theme_eguru v4.0.1(2022051900),the error occurs "Class 'theme_eguru\output\core\context_system' not found"
![1](https://user-images.githubusercontent.com/106827799/171902465-753e3817-fd24-4255-9d63-cc7619881ae8.png)
